### PR TITLE
Local dev database

### PR DESCRIPTION
**Pull request by josephmfaulkner**
This spins up a local, Dockerized and versioned database for the project. It includes migrations to seed it with the test data. I've included instructions to use it on the README. I checked this morning to see that this implementation reflects what we have out on our current dev database in AWS. The only thing it doesn't have is an extra 100 or so organization and action records. We could add those in as well but I don't think it's necessary at this time. Let me know.

### CODE REVIEW

**Review by kelfink — CHANGES_REQUESTED** [review]
@josephmfaulkner Great work.   Can you include instructions about configuring for local dev versus the shared one? I assume it would be comments in the README about editing the config.js

**Comment by josephmfaulkner** [comment]
@kelfink: Sorry for the late reply. Yes, I can make that change to the README file. 
By default, the software is setup to point to the local database (no harm in checking that config setting into version control).

**Comment by josephmfaulkner** [comment]
@kelfink: Okay, I've included instructions for how the DB configurations are handled. I also added the files to the .gitignore to prevent the credentials from being committed.

**Comment by josephmfaulkner** [comment]
I'm going to close this pull request and start a new one that merges to dev instead of master.

**Pull request closed without merging**
